### PR TITLE
[CSE-195] Put Explorer back in Explorer

### PR DESCRIPTION
**Pull request by pva701**

### CODE REVIEW

**Comment by akegalj** [comment]
@Pastafarianist 
> WIP until we fill in undefined

can you point which undefinedes exactly

**Comment by ksaric** [comment]
@Pastafarianist Did anyone try to run this? I tried running this now. Seems to me that the TLS is complicating things since I can't seem to connect to it?

**Comment by ksaric** [comment]
Still not working. The requests get to the server but it seems there are other things that are causing issues - so I'm guessing this means TLS is now off. 
For example, I can't seem to launch 3 nodes in _DEV_ mode - "Send to only 0 nodes, threshold is 2", and I can't seem to make it work in _testnet_ mode.
Can someone explain what happened to `bracketResourcesKademlia`?

**Comment by akegalj** [comment]
@ksaric this PR https://github.com/input-output-hk/cardano-sl-explorer/pull/195 fixes launch scripts. You can also try prod mode on qa cluster with it

**Comment by ksaric** [comment]
@akegalj I can't. We need to merge PR #195 with this one for me to test. I can't access the server because of TLS issue.

**Comment by ksaric** [comment]
Merged since the other PR's are failing.

**Pull request merged**
