### PR TITLE
[CSE-68] Update to latest `psc 0.11.5` and `Pux 10`

### PR DESCRIPTION
**Pull request by sectore**
As an exception  this PR comes with a lot of code changes (`1,468 additions` and `1,670 deletions`). Most of them (`~98%`) are syntax related and just `~2%` are changes of business logic. All these changes are needed to run latest `psc 0.11.5` and `Pux 10`.

### CODE REVIEW

**Comment by cleverca22** [comment]
```
error: syntax error, unexpected ID, expecting '{', at /home/travis/build/input-output-hk/cardano-sl-explorer/shell.nix:4:3
The command "./scripts/build.sh" exited with 1.
78.20s$ nix-shell --run "yarn test"
```
the main `frontend/scripts/build.sh` failed, so it didnt get far enough to generate `node_modules`, and now `rimraf` doesn't exist

**Comment by sectore** [comment]
> `error: syntax error, unexpected ID, expecting ...`

Oh, that ^ was my fault (vim input mode shortcut `ì`) :scream: Thanks @cleverca22 !

**Comment by domenkozar** [comment]
It's a really bad idea to bump PS version just before the release.

But if you insist due to a reason that's required to ship feature(s):

a)You'll need to install happy separately as here: https://github.com/input-output-hk/cardano-sl/blob/master/scripts/ci/travis.sh#L25

b) `frontend/purescript-derive-lenses.nix` will probably fail with the new version of PS, we will see what CI will says

**Comment by sectore** [comment]
@domenkozar I don't have any information about a release date of `Explorer`. If you have more information about this, share this internally via Slack please.

a) Could you give more information, where the command `stack install happy` (or similar) has to be added at Explorer project, please? Just because we don't have a `travis.sh` in Explorer. Feel free to push this fix into this `PR 152` here. 
b) Please don't use another version of `purescript-derive-lenses` as before. If it will fail, we can fork and fix it.

Thanks!

**Comment by akegalj** [comment]
I will communicate release dates on Mon

**Pull request merged**
