### PR TITLE
[CSE-120] Add endpoint to subscribe on new blocks with offset

### PR DESCRIPTION
**Pull request by Martoon-00**
This also applies some refactorings

### CODE REVIEW

**Comment by ksaric** [comment]
Regarding the issue https://issues.serokell.io/issue/CSE-139 and the discussion with @sectore before, I propose we always return last 5 or (ideally) 10 entries of the subscription regardless whether they are new or not - when the new block/transaction appears. 
On the client side they are called with `SocketBlocksUpdated` or `SocketTxsUpdated`.

I now agree that the solution with the number of total blocks/transactions inside the data structure is much better and can change it - https://issues.serokell.io/issue/CSE-133#comment=96-3558

We can take that approach on both the http and socket side and simplify things much more. The client side can just say which "page" it wants and the server can return it. Simple.

Forget offset, forget limit. We can modify the api call to have a `page` parameter and simplify.

**Comment by akegalj** [comment]
@ksaric 
> Forget offset, forget limit. We can modify the api call to have a page parameter and simplify.

explorer api will be used by third party providers like exchanges. Maybe their "page" is not the same as our page

**Comment by ksaric** [comment]
@akegalj Yes, and they can use the `limit` and `offset` versions of the API.

**Comment by ksaric** [comment]
I do want to add that we could just have a `?page=345&results=10` added and we could simplify the whole recalculation a lot.

**Comment by akegalj** [comment]
@ksaric go with your intuition then . If it simplifies things

**Comment by sectore** [comment]
> would remove all calculation from the client side

@ksaric The idea is great, but I don't think that the calculation on client side is a problem. 

For using current API of `?offset=x&limit=y` we just have to calculate an `offset`, which is very simple, e.g. here
https://github.com/input-output-hk/cardano-sl-explorer/blob/cardano-sl-0.4/frontend/src/Explorer/Update.purs#L228

And the value of `limit` is just a constant and does not have to be calculated.

So it might be not a big improvement as it seems (I'm speaking for front-end side only). Because by using `?page=345&results=10` we still have to know on front-end side what the current page and what the max. number of result are. We already have these two values in our state with `dbViewBlockPagination` (https://github.com/input-output-hk/cardano-sl-explorer/blob/cardano-sl-0.4/frontend/src/Explorer/State.purs#L39) and with `maxBlockRow` (https://github.com/input-output-hk/cardano-sl-explorer/blob/cardano-sl-0.4/frontend/src/Explorer/View/Blocks.purs#L35-L36). 

The only (small) improvement on front-end side is to save the (simple) calculation of the `offset`.

**Comment by ksaric** [comment]
@sectore Can you write that into https://issues.serokell.io/issue/CSE-140 please?

**Comment by ksaric** [comment]
In light of the comments from @sectore I'm merging this.

**Pull request merged**
