### PR TITLE
[CSE-56] Add docs generation. Added info in readme.

### PR DESCRIPTION
**Pull request by ksaric**
Added documentation generation, added some info to readme.

### CODE REVIEW

**Comment by domenkozar** [comment]
Can you also generate the docs on travis? I'll hook up to serve them.

**Comment by ksaric** [comment]
Sure thing, but give me a couple of days to provide a more readable documentation, now it's not very clear, it's generated by default. I was thinking of generating the endpoints API table, as seen in the documentation - https://cardano-docs.iohk.io/technical/wallet/, that would save us a lot of time in the long run. Also, that way we could never have outdated documentation - at least for the endpoints API.

**Comment by domenkozar** [comment]
Travis fails, you probably first need to `mkdir docs`

**Comment by domenkozar** [comment]
You will also need to do `nix-shell --run "stack exec --nix -- cardano-explorer-docs"`

**Comment by akegalj** [comment]
@ksaric can you check why travis is failing ⏫  https://travis-ci.org/input-output-hk/cardano-sl-explorer/builds/210548967

**Comment by ksaric** [comment]
Yep, found it. Consulted with @domenkozar, should work now.

**Comment by domenkozar** [comment]
There is one more error unrelated, coming from master as well:

```
./scripts/generate-backend-lenses.sh: 22: ./scripts/generate-backend-lenses.sh: cannot open src/Generated/Pos/Types/Core.purs: No such file
```

Are you all using `./scripts/build.sh` successfully? It seems to be broken.

**Comment by domenkozar** [comment]
I think it's a cache error, I'm merging this.

**Pull request merged**
