### PR TITLE
cardano-sl-explorer.cabal: use gold linker

### PR DESCRIPTION
**Pull request by domenkozar**
Link executables with gold, to speed up the build.

### CODE REVIEW

**Comment by domenkozar** [comment]
@ksaric can you fix the CI failures - they were from before my commit?

**Comment by ksaric** [comment]
I restarted the build, I don't think your commit messed anything up. I will merge my PR with `master` since other guys will start working with `master` tomorrow. 
You can create a PR to `cardano-sl-0.5`, I create a new branch and we can deploy from there.

**Comment by ksaric** [comment]
@domenkozar I think we can close this PR - https://travis-ci.org/input-output-hk/cardano-sl-explorer/builds/241594811#L2689-L2693

**Comment by domenkozar** [comment]
That's going to be fixed in https://github.com/input-output-hk/cardano-sl/pull/923

**Comment by ksaric** [comment]
@domenkozar Nice idea. Ok, when it's merged into `cardano-sl` `master` and the PR passes, we can merge.

**Comment by domenkozar** [comment]
@ksaric sure, meanwhile we should fix our frontend build: https://travis-ci.org/input-output-hk/cardano-sl-explorer/builds/241594811#L4088

**Comment by ksaric** [comment]
@domenkozar I think that the cause is the lack of compilation of the _explorer_. It worked otherwise.

**Comment by domenkozar** [comment]
@ksaric do you plan to backport 0.5 fixes to master?

**Comment by ksaric** [comment]
@domenkozar Yes.

**Comment by ksaric** [comment]
https://github.com/input-output-hk/cardano-sl-explorer/pull/144

**Pull request merged**
