### PR TITLE
[CSE-193] Extend genesis page

### PR DESCRIPTION
**Pull request by Pastafarianist**
Backend part done, frontend part pending.

### CODE REVIEW

**Comment by akegalj** [comment]
@Pastafarianist did we add a way to filter redeemed vs non-redeemed in the results on backend? 

This ^ can be done on frontend as well (the filtering) though

**Comment by Pastafarianist** [comment]
@akegalj no, we did not. Should we? It's about 30min work.

**Comment by Pastafarianist** [comment]
@akegalj I've just added it.

**Comment by akegalj** [comment]
Tested, seems its working ok. I wonder why there are no blocks on main page though. Will test 0.5 to double check before merging

**Pull request merged**
