### PR TITLE
[CSM-224, CSE-108] getAddressSummary throws for RedeemAddresses

### PR DESCRIPTION
**Pull request by Pastafarianist**

### CODE REVIEW

**Comment by Martoon-00** [comment]
Does it fix the issue?

**Comment by Pastafarianist** [comment]
No, that's why it's WIP. It only makes the error message clearer.

**Comment by Martoon-00** [comment]
Yep, sorry, didn't notice it at first

**Comment by Pastafarianist** [comment]
Now this also fixes CSE-108 as returning address types is useful for testing.

**Comment by akegalj** [comment]
@sectore In fact you are right, there is a missing `CAddressType`.

I will push the commit now after I test it locally. Thanks

**Comment by akegalj** [comment]
@sectore but looks like there is more to update in frontend now. I will leave this too you to have a look at Mon

**Comment by Pastafarianist** [comment]
Please DO NOT MERGE this PR until https://github.com/input-output-hk/cardano-sl/pull/304 is merged. And before merging we'll have to update the commit hash in `stack.yaml` to the latest commit from the aforementioned PR.

**Comment by akegalj** [comment]
@Pastafarianist is this still WIP ? If its not, would you mind resolving the conflicts and merging ?

**Pull request merged**
